name: rag
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  onnxruntime: ^1.4.1
  collection: ^1.18.0
  path_provider: ^2.1.4
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  objectbox_generator: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/models/